import { ScienceQuestion, SourceItem, TopicId } from './science-types';

export const scienceRoot =
  '/Users/rachel/Documents/我 iPad 上的文件/学习资料/新加坡P4/科学';

export const topicLabels: Record<TopicId, string> = {
  matter: 'Matter',
  heat: 'Heat',
  systems: 'Systems',
};

export const sourceLibrary: SourceItem[] = [
  {
    title: 'Primary Science Syllabus 2023',
    category: 'syllabus',
    path: `${scienceRoot}/primary-science-syllabus-2023_may24.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: 'P4 matter chapter',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/P4 matter chapter.pdf`,
    topicTags: ['matter'],
  },
  {
    title: 'matter章节常考知识点和实验题类型',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/matter章节常考知识点和实验题类型.pdf`,
    topicTags: ['matter'],
  },
  {
    title: 'How aro mass and volume of 2',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/How aro mass and volume of 2.pdf`,
    topicTags: ['matter'],
  },
  {
    title: 'P4 Heat Chapter',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/P4 Heat Chapter.pdf`,
    topicTags: ['heat'],
  },
  {
    title: 'P4 effect of heat chapter',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/P4 effect of heat chapter.pdf`,
    topicTags: ['heat'],
  },
  {
    title: 'The_Heat_Detective.key',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/The_Heat_Detective.key`,
    topicTags: ['heat'],
  },
  {
    title: 'Systems_In_Sync',
    category: 'chapter_notes',
    path: `${scienceRoot}/章节内容/Systems_In_Sync.pdf`,
    topicTags: ['systems'],
  },
  {
    title: 'MCQ_错题汇总',
    category: 'error_book',
    path: `${scienceRoot}/错题/MCQ_错题汇总.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: '科学错题集',
    category: 'error_book',
    path: `${scienceRoot}/错题/科学错题集.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: '2021 P4 Science Papers',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/2021 P4 Science Papers.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: '2022 P4 Science exam paper',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/2022 P4 Science exam paper.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: '2023 P4 Science Kiasu Exam Paper',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/2023 P4 Science Kiasu Exam Paper.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: '2024 P4 Science Full KiasuExamPaper',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/2024 P4 Science Full KiasuExamPaper.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: 'P4_Science_WA1_2025_CatholicHigh_Exam_Papers',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/P4_Science_WA1_2025_CatholicHigh_Exam_Papers.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: 'P4_Science_WA2_2025_NanHua_Exam_Papers',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/P4_Science_WA2_2025_NanHua_Exam_Papers.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: 'P4_Science_EOY_2025_PLMGS_Exam_Papers',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/P4_Science_EOY_2025_PLMGS_Exam_Papers.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
  {
    title: 'P4_Science_EOY_Rosyth_Exam_Papers',
    category: 'school_exam',
    path: `${scienceRoot}/名校试卷/P4_Science_EOY_Rosyth_Exam_Papers.pdf`,
    topicTags: ['matter', 'heat', 'systems'],
  },
];

export const questionBank: ScienceQuestion[] = [
  {
    id: 'mat-01',
    topic: 'matter',
    type: 'mcq',
    difficulty: 'foundation',
    sourceHint: 'Matter chapter notes + common exam question pattern',
    stem: 'A pupil places 50 mL of water into a measuring cylinder and then adds a marble. The water level rises to 58 mL. What is the volume of the marble?',
    options: [
      { id: 'A', text: '8 mL' },
      { id: 'B', text: '50 mL' },
      { id: 'C', text: '58 mL' },
      { id: 'D', text: '108 mL' },
    ],
    answer: 'A. 8 mL',
    explanation: 'The object volume equals the rise in water level: 58 minus 50 = 8 mL.',
    skills: ['displacement method', 'reading measuring cylinder'],
  },
  {
    id: 'mat-02',
    topic: 'matter',
    type: 'mcq',
    difficulty: 'standard',
    sourceHint: 'Matter chapter notes',
    stem: 'Which statement about mass and volume is correct?',
    options: [
      { id: 'A', text: 'Mass tells us how much space an object takes up.' },
      { id: 'B', text: 'Volume tells us how heavy an object is.' },
      { id: 'C', text: 'Mass is the amount of matter in an object.' },
      { id: 'D', text: 'Objects with the same volume must have the same mass.' },
    ],
    answer: 'C. Mass is the amount of matter in an object.',
    explanation: 'Mass measures the amount of matter, while volume measures space occupied.',
    skills: ['mass vs volume'],
  },
  {
    id: 'mat-03',
    topic: 'matter',
    type: 'short_open',
    difficulty: 'standard',
    sourceHint: '错题汇总常见开放题',
    stem: 'Ali says that a sponge has no volume because it is light. Explain why Ali is wrong.',
    answer: 'Ali is wrong because volume is the amount of space an object occupies. A sponge still takes up space even if it is light.',
    explanation: 'Students often confuse weight or mass with volume. The key idea is space occupied.',
    skills: ['scientific explanation', 'concept correction'],
  },
  {
    id: 'mat-04',
    topic: 'matter',
    type: 'experiment',
    difficulty: 'challenge',
    sourceHint: 'matter章节常考知识点和实验题类型',
    stem: 'You are given a stone, a beaker of water and a measuring cylinder. Describe how you would find the volume of the stone.',
    answer: 'Pour some water into the measuring cylinder and record the first reading. Carefully lower the stone fully into the water. Record the new reading. Subtract the first reading from the second reading to find the volume of the stone.',
    explanation: 'A complete answer includes the initial reading, full submersion and subtraction.',
    skills: ['planning steps', 'fair measurement'],
  },
  {
    id: 'heat-01',
    topic: 'heat',
    type: 'mcq',
    difficulty: 'foundation',
    sourceHint: 'P4 Heat Chapter',
    stem: 'When heat is added to most substances, what usually happens first?',
    options: [
      { id: 'A', text: 'They contract.' },
      { id: 'B', text: 'They expand.' },
      { id: 'C', text: 'They lose all mass.' },
      { id: 'D', text: 'They stop taking up space.' },
    ],
    answer: 'B. They expand.',
    explanation: 'Most materials expand when heated and contract when cooled.',
    skills: ['effect of heat'],
  },
  {
    id: 'heat-02',
    topic: 'heat',
    type: 'mcq',
    difficulty: 'standard',
    sourceHint: 'The_Heat_Detective',
    stem: 'Why is the metal lid of a glass jar easier to open after it is placed under warm water for a short time?',
    options: [
      { id: 'A', text: 'The lid melts slightly.' },
      { id: 'B', text: 'The glass contracts faster than the lid.' },
      { id: 'C', text: 'The metal lid expands and becomes looser.' },
      { id: 'D', text: 'The water adds extra force to the lid.' },
    ],
    answer: 'C. The metal lid expands and becomes looser.',
    explanation: 'Warmth causes the metal lid to expand, which helps loosen it.',
    skills: ['real-life application'],
  },
  {
    id: 'heat-03',
    topic: 'heat',
    type: 'short_open',
    difficulty: 'standard',
    sourceHint: 'Heat wrong-answer pattern',
    stem: 'A student filled a bottle to the brim with coloured water and placed it in the sun. After some time, water overflowed. Explain why.',
    answer: 'The coloured water was heated by the sun and expanded, so it occupied more space and overflowed from the bottle.',
    explanation: 'The expected link is: heating -> expansion -> more space occupied -> overflow.',
    skills: ['cause and effect explanation'],
  },
  {
    id: 'heat-04',
    topic: 'heat',
    type: 'experiment',
    difficulty: 'challenge',
    sourceHint: 'P4 effect of heat chapter',
    stem: 'A teacher wants to show that air expands when heated. Suggest a simple setup and state what observation would support the conclusion.',
    answer: 'Fit a balloon over the mouth of a bottle and place the bottle in warm water. The balloon inflates because the air in the bottle expands when heated.',
    explanation: 'The question tests setup plus the correct observable evidence.',
    skills: ['designing investigation', 'observation and conclusion'],
  },
  {
    id: 'sys-01',
    topic: 'systems',
    type: 'mcq',
    difficulty: 'foundation',
    sourceHint: 'Systems_In_Sync',
    stem: 'Which system helps a person breathe in oxygen and breathe out carbon dioxide?',
    options: [
      { id: 'A', text: 'Digestive system' },
      { id: 'B', text: 'Respiratory system' },
      { id: 'C', text: 'Skeletal system' },
      { id: 'D', text: 'Reproductive system' },
    ],
    answer: 'B. Respiratory system',
    explanation: 'The respiratory system is responsible for gas exchange.',
    skills: ['body systems'],
  },
  {
    id: 'sys-02',
    topic: 'systems',
    type: 'mcq',
    difficulty: 'standard',
    sourceHint: 'Systems_In_Sync + school exam style',
    stem: 'Which pair of plant parts work together to make food for the plant?',
    options: [
      { id: 'A', text: 'Leaf and stem' },
      { id: 'B', text: 'Flower and fruit' },
      { id: 'C', text: 'Root and seed' },
      { id: 'D', text: 'Stem and root hair' },
    ],
    answer: 'A. Leaf and stem',
    explanation: 'Leaves make food while the stem transports water and food to different parts.',
    skills: ['plant system interactions'],
  },
  {
    id: 'sys-03',
    topic: 'systems',
    type: 'short_open',
    difficulty: 'standard',
    sourceHint: '错题集常见系统题',
    stem: 'A plant is kept in a dark cupboard for many days. Its leaves turn yellow and the plant grows poorly. Explain why.',
    answer: 'The plant cannot get enough light to make food. Without enough food, the leaves become unhealthy and the plant grows poorly.',
    explanation: 'The key scientific idea is that leaves need light for food making.',
    skills: ['linking conditions to function'],
  },
  {
    id: 'sys-04',
    topic: 'systems',
    type: 'experiment',
    difficulty: 'challenge',
    sourceHint: 'School exam open-ended investigation',
    stem: 'A student wants to find out whether leaves are needed for a plant to make food. State one variable to keep the same and one observation to record.',
    answer: 'Keep the same: plant type, amount of water, or amount of light. Record: whether the leaf with access to light produces starch or remains healthy compared with the test leaf.',
    explanation: 'Investigation questions need fair test language and a measurable observation.',
    skills: ['fair test', 'variables and observation'],
  },
  {
    id: 'mix-01',
    topic: 'matter',
    type: 'mcq',
    difficulty: 'challenge',
    sourceHint: 'School exam mixed paper',
    stem: 'Three objects, P, Q and R, have the same volume. Q has the greatest mass and R has the least mass. Which statement must be true?',
    options: [
      { id: 'A', text: 'R is the biggest object.' },
      { id: 'B', text: 'Q contains more matter than P and R.' },
      { id: 'C', text: 'P and Q are made of the same material.' },
      { id: 'D', text: 'R has no air spaces.' },
    ],
    answer: 'B. Q contains more matter than P and R.',
    explanation: 'Greater mass means more matter, even when volume is the same.',
    skills: ['reasoning from comparison'],
  },
  {
    id: 'mix-02',
    topic: 'heat',
    type: 'short_open',
    difficulty: 'challenge',
    sourceHint: 'Wrong-book misconception question',
    stem: 'Ben says, “Objects become heavier when heated because they get bigger.” Do you agree? Explain.',
    answer: 'No. Heating usually makes an object expand, but expansion does not mean its mass increases. The object becomes bigger because it takes up more space, not because more matter is added.',
    explanation: 'This targets the common confusion between size and mass.',
    skills: ['argument evaluation'],
  },
];
